### ISSUE TITLE
Users need a node status page

### ISSUE THREAD

**Issue by veox** [vipnode/vipnode.org#1]
Hello! We've [chatted on reddit](https://www.reddit.com/r/ethdev/comments/85l52t/having_trouble_connecting_with_geth_in_light_mode/dw8bi0i/). :)

I've stopped my light client y-day, and started it today (about 12-18 hours down-time). A connection between it and the `vipnode` server was not estabilished automatically, ~~JIC, the IP/port were properly forwarded (verified using `netcat` from a remote machine).~~ completely due to my own fault.

I've added the `vipnode` as a peer manually ~~(which I was savvy enough to save)~~ (had it as a `static_node` on a different machine by accident), which worked fine.

In trying to ~~determine why it hasn't happened automatically~~ clear up my own confusion, I wondered if it's perhaps the `vipnode` server being down.

It would be helpful if you listed the node on https://ethstats.net/, or provided a node status indication on https://vipnode.shazow.net/.

**Comment by samparsky** [comment]
Hey @shazow I can help work on this.

**Comment by shazow** [comment]
@samparsky Thanks but this requires the backend to be wired up for publishing health checks first. :)

**Comment by veox** [comment]
I see `subj` at https://vipnode.org/status, so this can probably be closed.

**Comment by shazow** [comment]
@veox You're right, good call!
