### ISSUE TITLE
ContractPool DApp Design

### ISSUE THREAD

**Issue by shazow** [vipnode/vipnode.org#20]
This is for the `/pool` endpoint. A web3-enabled browser (metamask) is required to view it properly.

Current dump-all-the-elements layout:

![image](https://user-images.githubusercontent.com/6292/47026251-06a7d600-d133-11e8-8ad0-6953bc19731c.png)

Requirements:
- Make it clear that this is experimental and that money can be lost or should be considered a donation.
- There are 3 "widgets" here:
  1. Your current wallet status (network, wallet dropdown, could also add your native wallet balance--which is different from your balance with the contract)
  2. Contract balance (how much money you have locked in the contract that will be withdrawn from as you utilize the vipnode pool), and adding to the balance
  3. Authorizing nodeIDs to your wallet (and de-authorizing). Vipnode Pool users will be directed to this page with that field pre-filled, such as: `/pool?enode=19b5013d24243a659bda7f1df13933bb05820ab6c3ebf6b5e0854848b97e1f7e308f703466e72486c5bc7fe8ed402eb62f6303418e05d330a5df80738ac974f6`
- Errors and success messages should render properly.

Overall need to work on wording and layout to make sure it's clear what's going on without being overwhelming.

There are various scenarios here (maybe we should sketch out draft layouts for each):
- Brand new user who needs to add a balance
- Existing balance but adding a new nodeID
- Existing user who wants to cash out (request withdraw).
- Anything else?

It's not clear whether we should require a balance before whitelisting a node (makes sense to do that, just to reduce spam?).

**Comment by shazow** [comment]
Design merged.

**Comment by shazow** [comment]
Had to add a separate deposit value (vs balance on pool), so I consolidated the form into one line:

## On landing

![image](https://user-images.githubusercontent.com/6292/47736240-a80b4d80-dc44-11e8-970d-1b5a251db230.png)

## On clicking `Add Deposit`

![image](https://user-images.githubusercontent.com/6292/47736255-b0638880-dc44-11e8-882b-6a826ee01668.png)

There's some off-by-one-pixel design inconsistency (seems skeleton sets pixel height, our scss sets rem height, and that specific form is setting line-height), but good enough for now.

**Comment by limedaring** [comment]
I think that looks great :)
